version: '3'

services:
  kafka:
    build: ./kafka
    ports:
      - '9092:9092'
    volumes:
      - ./src:/home/code
    environment:
      - ADVERTISED_HOST=172.20.0.5
      - ADVERTISED_PORT=9092
    networks:
            frontend:
                ipv4_address: 172.20.0.5

  spark:
    build: ./spark_streaming
    ports:
      - '8888:8888'
    volumes:
      - ./src:/home/code
      - ../data:/home/data
    environment:
      - PYSPARK_SUBMIT_ARGS=--packages org.apache.spark:spark-streaming-kafka-0-8_2.11:2.0.2 pyspark-shell
    networks:
            frontend:
                ipv4_address: 172.20.0.6

  redis:
    image: redis
    ports:
      - '6379:6379'
    networks:
            frontend:
                ipv4_address: 172.20.0.7

  django:
    build: ./django
    ports:
      - '8000:8000'
    volumes:
      - ./src/webapp/mysite:/usr/src/app
    networks:
            frontend:
                ipv4_address: 172.20.0.8


networks:
  frontend:
    ipam:
      config:
        - subnet: 172.20.0.0/24