version: '3'

services:
  kafka:
    build: ./kafka
    ports:
      - '9092:9092'
    volumes:
      - ./src:/home/code
    environment:
      - ADVERTISED_HOST=172.20.0.5
      - ADVERTISED_PORT=9092
    networks:
            frontend:
                ipv4_address: 172.20.0.5

  spark:
    image: jupyter/pyspark-notebook
    ports:
      - '8888:8888'
    volumes:
      - ./src:/home/code
    environment:
      - PYSPARK_SUBMIT_ARGS=--packages org.apache.spark:spark-streaming-kafka-0-8_2.11:2.0.2 pyspark-shell
    networks:
            frontend:
                ipv4_address: 172.20.0.6


networks:
  frontend:
    ipam:
      config:
        - subnet: 172.20.0.0/24